INSERT INTO PROFESSION (ID, NAME) VALUES (1, 'программист');
INSERT INTO PROFESSION (ID, NAME) VALUES (2, 'бухгалтер');
INSERT INTO PROFESSION (ID, NAME) VALUES (3, 'секретарь');

INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'отдел разработки ПО');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (2, 'бухгалтерия');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (3, 'отдел кадров');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (4, 'юридический отдел');

INSERT INTO PERSON (ID, TAB_NUMBER, NAME, PROFESSION_ID, DEPARTMENT_ID) VALUES(1, 230,'Иванов Иван Иванович', 1, 1);
INSERT INTO PERSON (ID, TAB_NUMBER, NAME, PROFESSION_ID, DEPARTMENT_ID) VALUES(2, 231, 'Петров Пётр Сергеевич', 2, 4);
INSERT INTO PERSON (ID, TAB_NUMBER, NAME, PROFESSION_ID, DEPARTMENT_ID) VALUES(3, NULL, 'Сидоров Василий Иванович', 2, 2);

