DROP TABLE IF EXISTS PROFESSION;
CREATE TABLE PROFESSION(
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    NOTES VARCHAR(255));

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT(
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    NOTES VARCHAR(255));

DROP TABLE IF EXISTS PERSON;
CREATE TABLE PERSON (
    ID LONG PRIMARY KEY AUTO_INCREMENT,
    TAB_NUMBER INTEGER,
    NAME VARCHAR(255) NOT NULL,
    NOTES VARCHAR(255),
    PROFESSION_ID LONG NOT NULL,
    DEPARTMENT_ID LONG NOT NULL);

ALTER TABLE PERSON ADD FOREIGN KEY (PROFESSION_ID) REFERENCES PROFESSION(ID);
ALTER TABLE PERSON ADD FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID);
